export const VISITOR_LISTING_SCREEN = 'VISITOR_LISTING_SCREEN',
  VISITOR_CREATE_SCREEN = 'VISITOR_CREATE_SCREEN',
  NEWS_LISTING_SCREEN = 'NEWS_LISTING_SCREEN',
  VISITOR_STACK = 'Visitors',
  NEWS_STACK = 'Latest News';
